#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════╗
║              SEO AGENT PRO — Multi-Model Edition                 ║
║                                                                  ║
║  Supports: Anthropic · OpenRouter · Groq                         ║
║  Models:   Claude · GPT-4o · Gemini · Llama · Mistral · DeepSeek║
╚══════════════════════════════════════════════════════════════════╝

Usage:
  python main.py --keyword "best laptop for students"
  python main.py --keyword "best laptop" --model gpt-4o --niche "tech"
  python main.py --mode cluster  --keyword "laptop"
  python main.py --mode calendar --keyword "tech" --niche "technology blog" --months 3
  python main.py --models          (list all available models)
  python main.py --stats           (show memory stats)
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

import memory as mem_module
import modules as agent
from config import DEFAULT_MODEL, SETTINGS
from llm_router import c, list_models


# ──────────────────────────────────────────────────────────────
#  Output helpers
# ──────────────────────────────────────────────────────────────

OUTPUT_DIR = Path(SETTINGS["output_dir"])

def _save(filename: str, content: str) -> Path:
    OUTPUT_DIR.mkdir(exist_ok=True)
    path = OUTPUT_DIR / filename
    path.write_text(content, encoding="utf-8")
    print(c("green", f"  ✓ Saved → {path}"))
    return path

def _slug(text: str) -> str:
    return re.sub(r"[^\w\s-]", "", text).replace(" ", "_")[:35]

def _ts() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M")

def _header(title: str) -> None:
    line = "═" * 62
    print(f"\n{c('purple', line)}")
    print(c("bold", f"  {title}"))
    print(c("purple", line))


# ──────────────────────────────────────────────────────────────
#  Run modes
# ──────────────────────────────────────────────────────────────

def run_full(keyword: str, niche: str, model: str, months: int) -> None:
    memory = mem_module.load()
    ts     = _ts()
    slug   = _slug(keyword)

    _header(f"SEO Agent Pro — Full Pipeline  [{model}]")
    print(f"""
  Keyword   : {c('bold', keyword)}
  Niche     : {c('bold', niche or 'auto-detect')}
  Model     : {c('cyan', model)}
  Articles  : {len(memory['articles_written'])} in memory
  Time      : {datetime.now().strftime('%Y-%m-%d %H:%M')}
""")

    # ── 1. Competitor analysis ─────────────────────────────────
    competitor_data = agent.analyze_competitors(keyword, model)

    # ── 2. Strategy decision ───────────────────────────────────
    strategy = agent.decide_strategy(
        keyword, competitor_data,
        len(memory["articles_written"]), model
    )

    # ── 3. Write article ───────────────────────────────────────
    article = agent.write_article(keyword, strategy, model)
    _save(f"{slug}_{ts}.md", article)

    # ── 4. CTR optimization ────────────────────────────────────
    ctr = agent.optimize_ctr(keyword, article, model)

    # ── 5. Keyword cluster (V3) ────────────────────────────────
    cluster = agent.build_cluster(keyword, niche, model)
    _save(f"cluster_{slug}_{ts}.json",
          json.dumps(cluster, ensure_ascii=False, indent=2))

    # ── 6. Content calendar (V3) ───────────────────────────────
    if niche:
        calendar = agent.build_calendar(keyword, niche, months, model)
        _save(f"calendar_{slug}_{ts}.json",
              json.dumps(calendar, ensure_ascii=False, indent=2))
    else:
        calendar = []

    # ── 7. Authority score (V3) ────────────────────────────────
    if niche and len(memory["articles_written"]) >= 1:
        authority = agent.score_authority(niche, memory["articles_written"], model)
        mem_module.record_authority(memory, niche, authority)

    # ── 8. Update memory ───────────────────────────────────────
    mem_module.record_article(memory, keyword, article, model)
    mem_module.record_cluster(memory, keyword, cluster)

    # ── Final report ───────────────────────────────────────────
    report = f"""# SEO Agent Pro — Report
**Keyword:** {keyword}
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Model:** {model}

---

## Recommended Title
{ctr.get('recommended_title', '')}

## Recommended Meta Description
{ctr.get('recommended_description', '')}

## Strategy
- Type: {strategy.get('strategy', '').upper()}
- Angle: {strategy.get('unique_angle', '')}
- Target length: {strategy.get('ideal_length', 0)} words
- Reasoning: {strategy.get('reasoning', '')}

## Keyword Cluster
- Pillar: {cluster.get('pillar', {}).get('keyword', '')}
- Supporting topics: {len(cluster.get('clusters', []))}
- Quick wins: {len(cluster.get('quick_wins', []))}

## Output Files
- Article  : output/{slug}_{ts}.md
- Cluster  : output/cluster_{slug}_{ts}.json
{'- Calendar: output/calendar_' + slug + '_' + ts + '.json' if niche else ''}
- Report   : output/report_{slug}_{ts}.md

---
*Generated by SEO Agent Pro*
"""

    _save(f"report_{slug}_{ts}.md", report)

    _header("Pipeline Complete")
    print(f"""
  {c('green', '✓')} Article   →  output/{slug}_{ts}.md
  {c('green', '✓')} Cluster   →  output/cluster_{slug}_{ts}.json
  {c('green', '✓')} Report    →  output/report_{slug}_{ts}.md
  {c('green', '✓')} Memory    →  {SETTINGS['memory_file']}

  {c('yellow', 'Summary')}
  Clusters ready  : {len(cluster.get('clusters', []))}
  Calendar items  : {len(calendar)}
  Total articles  : {len(memory['articles_written'])}
""")


def run_article(keyword: str, model: str) -> None:
    memory = mem_module.load()
    ts     = _ts()
    slug   = _slug(keyword)

    _header(f"Article Mode  [{model}]")

    comp     = agent.analyze_competitors(keyword, model)
    strategy = agent.decide_strategy(keyword, comp, len(memory["articles_written"]), model)
    article  = agent.write_article(keyword, strategy, model)
    ctr      = agent.optimize_ctr(keyword, article, model)

    output = f"""---
title: {ctr.get('recommended_title', keyword)}
description: {ctr.get('recommended_description', '')}
keyword: {keyword}
model: {model}
date: {datetime.now().strftime('%Y-%m-%d')}
---

{article}
"""
    _save(f"{slug}_{ts}.md", output)
    mem_module.record_article(memory, keyword, article, model)


def run_cluster(keyword: str, niche: str, model: str) -> None:
    memory = mem_module.load()
    ts     = _ts()
    slug   = _slug(keyword)

    _header(f"Cluster Mode  [{model}]")

    result = agent.build_cluster(keyword, niche, model)
    _save(f"cluster_{slug}_{ts}.json", json.dumps(result, ensure_ascii=False, indent=2))
    mem_module.record_cluster(memory, keyword, result)


def run_calendar(keyword: str, niche: str, months: int, model: str) -> None:
    ts   = _ts()
    slug = _slug(keyword)

    _header(f"Calendar Mode  [{model}]")

    result = agent.build_calendar(keyword, niche or keyword, months, model)
    _save(f"calendar_{slug}_{ts}.json", json.dumps(result, ensure_ascii=False, indent=2))


def run_audit(slug_target: str, model: str) -> None:
    _header(f"Audit Mode  [{model}]")

    index_path = Path("public/content/articles-index.json")
    if not index_path.exists():
        print(c("red", "  ✗ Articles index not found."))
        return

    articles = json.loads(index_path.read_text(encoding="utf-8"))

    # Filter if specific slug provided, else do a sample or latest
    if slug_target:
        targets = [a for a in articles if a["slug"] == slug_target]
    else:
        print(c("dim", "  · No slug provided, auditing 3 latest articles..."))
        targets = articles[:3]

    if not targets:
        print(c("red", f"  ✗ No articles found matching: {slug_target}"))
        return

    for item in targets:
        slug = item["slug"]

        # Determine path (partitioned)
        s = re.sub(r'[^a-z0-9]', '-', slug.lower())
        s = re.sub(r'-+', '-', s).strip('-')

        c1 = s[0] if len(s) > 0 else '_'
        c2 = s[1] if len(s) > 1 else '_'
        c3 = s[2] if len(s) > 2 else '_'

        article_path = Path(f"public/content/articles/{c1}/{c2}/{c3}/{slug}.md")

        if not article_path.exists():
            # Try legacy non-partitioned path just in case
            article_path = Path(f"public/content/articles/{slug}.md")

        if not article_path.exists():
            print(c("yellow", f"  ⚠ Article file not found: {article_path}"))
            continue

        print(c("cyan", f"\n▸ Reading article: {slug}"))
        content = article_path.read_text(encoding="utf-8")
        # Strip frontmatter if possible
        body = re.sub(r'^---[\s\S]*?---', '', content).strip()

        audit_result = agent.audit_content(item.get("title", slug), body, item, model)

        _save(f"audit_{slug}_{_ts()}.json", json.dumps(audit_result, ensure_ascii=False, indent=2))


# ──────────────────────────────────────────────────────────────
#  Entry point
# ──────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="seo-agent",
        description="SEO Agent Pro — Multi-model SEO content pipeline",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "--mode",
        choices=["full", "article", "cluster", "calendar", "audit"],
        default="full",
        help=(
            "full     → Complete V2+V3 pipeline  (default)\n"
            "article  → Single article only\n"
            "cluster  → Keyword cluster map only\n"
            "calendar → Publishing calendar only\n"
            "audit    → Audit existing articles"
        ),
    )
    parser.add_argument("--keyword", help='Target keyword, e.g. "best laptop for students"')
    parser.add_argument("--niche",   default="", help='Content niche, e.g. "technology"')
    parser.add_argument("--model",   default=DEFAULT_MODEL, help=f"Model name from config.py (default: {DEFAULT_MODEL})")
    parser.add_argument("--months",  type=int, default=3, help="Calendar duration in months (default: 3)")
    parser.add_argument("--models",  action="store_true", help="List all available models and exit")
    parser.add_argument("--stats",   action="store_true", help="Show memory stats and exit")

    args = parser.parse_args()

    # ── Info-only flags ────────────────────────────────────────
    if args.models:
        print(f"\n{c('bold', 'Available Models')}")
        list_models()
        print()
        return

    if args.stats:
        memory = mem_module.load()
        mem_module.print_stats(memory)
        return

    # ── Keyword required for all run modes ─────────────────────
    if not args.keyword:
        parser.error("--keyword is required. Example: --keyword \"best laptop\"")

    # ── Dispatch ───────────────────────────────────────────────
    try:
        if args.mode == "full":
            run_full(args.keyword, args.niche, args.model, args.months)
        elif args.mode == "article":
            run_article(args.keyword, args.model)
        elif args.mode == "cluster":
            run_cluster(args.keyword, args.niche, args.model)
        elif args.mode == "calendar":
            run_calendar(args.keyword, args.niche, args.months, args.model)
        elif args.mode == "audit":
            run_audit(args.keyword, args.model)

    except KeyboardInterrupt:
        print(c("yellow", "\n\n  ⚠  Stopped by user."))
        sys.exit(0)


if __name__ == "__main__":
    main()
