<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - ExtensionTo</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
						padding: 2rem;
						background-color: #f8f9fa;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 2rem;
						border-radius: 8px;
						box-shadow: 0 4px 6px rgba(0,0,0,0.1);
					}
					h1 {
						color: #1a73e8;
						margin-top: 0;
					}
					p {
						font-size: 0.9rem;
						color: #666;
						line-height: 1.6;
					}
					.stats {
						display: flex;
						gap: 20px;
						margin-bottom: 2rem;
						padding: 1rem;
						background: #f1f3f4;
						border-radius: 4px;
					}
					.stat-item {
						display: flex;
						flex-direction: column;
					}
					.stat-value {
						font-size: 1.2rem;
						font-weight: bold;
						color: #1a73e8;
					}
					.stat-label {
						font-size: 0.75rem;
						text-transform: uppercase;
						color: #5f6368;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 1rem;
					}
					th {
						text-align: left;
						padding: 12px;
						background-color: #f1f3f4;
						border-bottom: 2px solid #ddd;
						font-weight: 600;
					}
					td {
						padding: 12px;
						border-bottom: 1px solid #eee;
						word-break: break-all;
					}
					tr:hover {
						background-color: #f8f9fa;
					}
					a {
						color: #1a73e8;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.priority-high {
						color: #d93025;
						font-weight: bold;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p>
						Generated by <strong>ExtensionTo</strong> to help search engines like Google and Bing discover our content.
						You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.
					</p>

					<xsl:if test="sitemap:sitemapindex">
						<div class="stats">
							<div class="stat-item">
								<span class="stat-value"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></span>
								<span class="stat-label">Total Sitemaps</span>
							</div>
						</div>
						<table>
							<thead>
								<tr>
									<th>Sitemap URL</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<xsl:variable name="itemURL">
												<xsl:value-of select="sitemap:loc"/>
											</xsl:variable>
											<a href="{$itemURL}">
												<xsl:value-of select="sitemap:loc"/>
											</a>
										</td>
										<td>
											<xsl:value-of select="sitemap:lastmod"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<xsl:if test="sitemap:urlset">
						<div class="stats">
							<div class="stat-item">
								<span class="stat-value"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span>
								<span class="stat-label">Total URLs</span>
							</div>
							<div class="stat-item">
								<span class="stat-value"><xsl:value-of select="count(sitemap:urlset/sitemap:url[contains(sitemap:loc, '/blog/')])"/></span>
								<span class="stat-label">Articles</span>
							</div>
							<div class="stat-item">
								<span class="stat-value"><xsl:value-of select="count(sitemap:urlset/sitemap:url[contains(sitemap:loc, '/extension/')])"/></span>
								<span class="stat-label">Extensions</span>
							</div>
							<div class="stat-item">
								<span class="stat-value"><xsl:value-of select="count(sitemap:urlset/sitemap:url[starts-with(sitemap:lastmod, '2026-04')])"/></span>
								<span class="stat-label">April 2026 Updates</span>
							</div>
						</div>
						<table>
							<thead>
								<tr>
									<th>URL</th>
									<th>Priority</th>
									<th>Change Freq.</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<xsl:variable name="itemURL">
												<xsl:value-of select="sitemap:loc"/>
											</xsl:variable>
											<a href="{$itemURL}">
												<xsl:value-of select="sitemap:loc"/>
											</a>
										</td>
										<td>
											<xsl:choose>
												<xsl:when test="sitemap:priority &gt; 0.7">
													<span class="priority-high"><xsl:value-of select="sitemap:priority"/></span>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="sitemap:priority"/>
												</xsl:otherwise>
											</xsl:choose>
										</td>
										<td>
											<xsl:value-of select="sitemap:changefreq"/>
										</td>
										<td>
											<xsl:value-of select="sitemap:lastmod"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
